language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-21.1.2
  - android-21
  - extra-android-m2repository
  - extra-android-support

  licenses:
  - 'android-sdk-license.*'

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

sudo: false

script: 'travis_retry ./gradlew build --parallel'

after_success:
- scripts/travis-sonatype-publish.sh
- ./gradlew jacocoTestReport coveralls
